[2021-03-29 23:14:29,266] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-03-28T00:00:00+00:00 [queued]>
[2021-03-29 23:14:29,322] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-03-28T00:00:00+00:00 [queued]>
[2021-03-29 23:14:29,323] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-29 23:14:29,324] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-29 23:14:29,325] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-29 23:14:29,420] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_2> on 2021-03-28T00:00:00+00:00
[2021-03-29 23:14:29,448] {standard_task_runner.py:52} INFO - Started process 57 to run task
[2021-03-29 23:14:29,486] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-03-28T00:00:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpq93c62_6', '--error-file', '/tmp/tmpyuyz615p']
[2021-03-29 23:14:29,487] {standard_task_runner.py:77} INFO - Job 6: Subtask runme_2
[2021-03-29 23:14:29,734] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_2 2021-03-28T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-03-29 23:14:29,879] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_2
AIRFLOW_CTX_EXECUTION_DATE=2021-03-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-28T00:00:00+00:00
[2021-03-29 23:14:29,884] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-29 23:14:29,887] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_2__20210328" && sleep 1
[2021-03-29 23:14:29,919] {bash.py:169} INFO - Output:
[2021-03-29 23:14:29,922] {bash.py:173} INFO - example_bash_operator__runme_2__20210328
[2021-03-29 23:14:30,924] {bash.py:177} INFO - Command exited with return code 0
[2021-03-29 23:14:30,971] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20210328T000000, start_date=20210329T231429, end_date=20210329T231430
[2021-03-29 23:14:31,024] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-29 23:14:31,068] {local_task_job.py:146} INFO - Task exited with return code 0
