[2021-04-14 13:28:25,373] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-04-12T00:00:00+00:00 [queued]>
[2021-04-14 13:28:25,766] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-04-12T00:00:00+00:00 [queued]>
[2021-04-14 13:28:25,803] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:25,871] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-14 13:28:25,916] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:26,292] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_2> on 2021-04-12T00:00:00+00:00
[2021-04-14 13:28:26,551] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-04-12T00:00:00+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpe87ddwnq', '--error-file', '/tmp/tmpijrhdk5u']
[2021-04-14 13:28:26,721] {standard_task_runner.py:77} INFO - Job 29: Subtask runme_2
[2021-04-14 13:28:26,416] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2021-04-14 13:28:28,045] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_2 2021-04-12T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-04-14 13:28:28,782] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_2
AIRFLOW_CTX_EXECUTION_DATE=2021-04-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-12T00:00:00+00:00
[2021-04-14 13:28:28,889] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-14 13:28:28,907] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_2__20210412" && sleep 1
[2021-04-14 13:28:29,025] {bash.py:169} INFO - Output:
[2021-04-14 13:28:29,040] {bash.py:173} INFO - example_bash_operator__runme_2__20210412
[2021-04-14 13:28:30,046] {bash.py:177} INFO - Command exited with return code 0
[2021-04-14 13:28:30,375] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20210412T000000, start_date=20210414T132825, end_date=20210414T132830
[2021-04-14 13:28:30,679] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-14 13:28:30,718] {local_task_job.py:146} INFO - Task exited with return code 0
