[2021-03-29 23:14:29,220] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-03-27T00:00:00+00:00 [queued]>
[2021-03-29 23:14:29,264] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-03-27T00:00:00+00:00 [queued]>
[2021-03-29 23:14:29,265] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-29 23:14:29,266] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-29 23:14:29,267] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-29 23:14:29,320] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_2> on 2021-03-27T00:00:00+00:00
[2021-03-29 23:14:29,345] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-03-27T00:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpdr874h4g', '--error-file', '/tmp/tmpb04k449i']
[2021-03-29 23:14:29,354] {standard_task_runner.py:77} INFO - Job 12: Subtask runme_2
[2021-03-29 23:14:29,333] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2021-03-29 23:14:29,623] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_2 2021-03-27T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-03-29 23:14:29,825] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_2
AIRFLOW_CTX_EXECUTION_DATE=2021-03-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-27T00:00:00+00:00
[2021-03-29 23:14:29,830] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-29 23:14:29,841] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_2__20210327" && sleep 1
[2021-03-29 23:14:29,896] {bash.py:169} INFO - Output:
[2021-03-29 23:14:29,914] {bash.py:173} INFO - example_bash_operator__runme_2__20210327
[2021-03-29 23:14:30,921] {bash.py:177} INFO - Command exited with return code 0
[2021-03-29 23:14:30,966] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20210327T000000, start_date=20210329T231429, end_date=20210329T231430
[2021-03-29 23:14:31,020] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-29 23:14:31,053] {local_task_job.py:146} INFO - Task exited with return code 0
