[2021-04-14 13:28:25,022] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-04-13T00:00:00+00:00 [queued]>
[2021-04-14 13:28:25,198] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-04-13T00:00:00+00:00 [queued]>
[2021-04-14 13:28:25,199] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:25,200] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-14 13:28:25,213] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:25,334] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2021-04-13T00:00:00+00:00
[2021-04-14 13:28:25,401] {standard_task_runner.py:52} INFO - Started process 62 to run task
[2021-04-14 13:28:25,504] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-04-13T00:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpmp7xogyl', '--error-file', '/tmp/tmp75yi7k7q']
[2021-04-14 13:28:25,508] {standard_task_runner.py:77} INFO - Job 26: Subtask runme_0
[2021-04-14 13:28:26,782] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_0 2021-04-13T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-04-14 13:28:27,769] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2021-04-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-13T00:00:00+00:00
[2021-04-14 13:28:27,784] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-14 13:28:27,788] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_0__20210413" && sleep 1
[2021-04-14 13:28:27,891] {bash.py:169} INFO - Output:
[2021-04-14 13:28:27,913] {bash.py:173} INFO - example_bash_operator__runme_0__20210413
[2021-04-14 13:28:28,970] {bash.py:177} INFO - Command exited with return code 0
[2021-04-14 13:28:29,784] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20210413T000000, start_date=20210414T132825, end_date=20210414T132829
[2021-04-14 13:28:30,151] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-14 13:28:30,267] {local_task_job.py:146} INFO - Task exited with return code 0
