[2021-04-14 13:28:33,264] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-04-13T00:00:00+00:00 [queued]>
[2021-04-14 13:28:33,330] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-04-13T00:00:00+00:00 [queued]>
[2021-04-14 13:28:33,340] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:33,341] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-14 13:28:33,342] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:33,453] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-04-13T00:00:00+00:00
[2021-04-14 13:28:33,471] {standard_task_runner.py:52} INFO - Started process 96 to run task
[2021-04-14 13:28:33,505] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', '2021-04-13T00:00:00+00:00', '--job-id', '39', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmph7oub7ip', '--error-file', '/tmp/tmp14pp9smv']
[2021-04-14 13:28:33,522] {standard_task_runner.py:77} INFO - Job 39: Subtask run_after_loop
[2021-04-14 13:28:33,806] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.run_after_loop 2021-04-13T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-04-14 13:28:34,110] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-04-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-13T00:00:00+00:00
[2021-04-14 13:28:34,117] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-14 13:28:34,126] {bash.py:158} INFO - Running command: echo 1
[2021-04-14 13:28:34,151] {bash.py:169} INFO - Output:
[2021-04-14 13:28:34,158] {bash.py:173} INFO - 1
[2021-04-14 13:28:34,159] {bash.py:177} INFO - Command exited with return code 0
[2021-04-14 13:28:34,264] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20210413T000000, start_date=20210414T132833, end_date=20210414T132834
[2021-04-14 13:28:34,411] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-14 13:28:34,489] {local_task_job.py:146} INFO - Task exited with return code 0
