[2021-04-14 13:28:24,856] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-04-12T00:00:00+00:00 [queued]>
[2021-04-14 13:28:25,103] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-04-12T00:00:00+00:00 [queued]>
[2021-04-14 13:28:25,104] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:25,108] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-14 13:28:25,109] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:25,250] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2021-04-12T00:00:00+00:00
[2021-04-14 13:28:25,259] {standard_task_runner.py:52} INFO - Started process 61 to run task
[2021-04-14 13:28:25,334] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-04-12T00:00:00+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpegqpiagn', '--error-file', '/tmp/tmpvdvr_hrr']
[2021-04-14 13:28:25,357] {standard_task_runner.py:77} INFO - Job 25: Subtask runme_0
[2021-04-14 13:28:26,098] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_0 2021-04-12T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-04-14 13:28:27,215] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2021-04-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-12T00:00:00+00:00
[2021-04-14 13:28:27,226] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-14 13:28:27,240] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_0__20210412" && sleep 1
[2021-04-14 13:28:27,448] {bash.py:169} INFO - Output:
[2021-04-14 13:28:27,488] {bash.py:173} INFO - example_bash_operator__runme_0__20210412
[2021-04-14 13:28:28,464] {bash.py:177} INFO - Command exited with return code 0
[2021-04-14 13:28:28,885] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20210412T000000, start_date=20210414T132824, end_date=20210414T132828
[2021-04-14 13:28:29,931] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-14 13:28:30,113] {local_task_job.py:146} INFO - Task exited with return code 0
